### ISSUE TITLE
Don't work, I miss something?

### ISSUE THREAD

**Issue by Carantin** [superseva/sound-link#4]
Hi, first thanks for the module, i search for this very long time. xD
now my question. 

when I write the code HTML, either by putting the original code or through the macro, don't work. 
![foto 1](https://user-images.githubusercontent.com/85190325/121148619-3951f000-c842-11eb-9827-e3beafda09ac.jpg)
![foto 2](https://user-images.githubusercontent.com/85190325/121148625-3a831d00-c842-11eb-8ba4-4a7815efb461.jpg)

The first image is the edition mode, the second, the normal. have I misspelled the code?

**Comment by superseva** [comment]
Hi, you need to put the link in the HTML part of the editor.
![sound-link-1](https://user-images.githubusercontent.com/4093045/121170073-049b6400-c855-11eb-956f-5dbfe00deae0.jpg)
![sound-link-2](https://user-images.githubusercontent.com/4093045/121170090-082eeb00-c855-11eb-8b34-c581a32c9e3c.jpg)
Then save and save the editor.

I've tried to work on just dragging the sound on to the editor but it is very hard since it clashes with the core Foundry recognition of entities and what can be dragged

**Comment by Carantin** [comment]
Ohhh, thanks, now yes.
